### ISSUE TITLE
Upgrading from 1.x to 2.x, missing accessors

### ISSUE THREAD

**Issue by nicolasrouanne** [lwe/simple_enum#139]
I'm currently in the process of upgrading my Rails application from `3.2` to `4.0` (and upwards to 5.1 but that's another story). As part of that upgrade, **I changed `simple_enum` version from `1.6.9` to `2.3.1`.**

I find that **newer _accessors_ are not working**, especially **scopes**.

Here is my model
```ruby
class Season < ActiveRecord::Base
  as_enum :name, low: 0, medium: 1, high: 2
end
```

When I try finding the `low` season (or seasons), it will fail
```ruby
Season.low #fail
Season.lows #fail

# error
NoMethodError: undefined method `lows' for #<Class:0x007f8415a11f08>
```

I believe it is because the accessor method where not generated at the time of the migration. Is there a way I can make it work?

I managed to get it working using the _column_name_ but I believe it limits the use of `simple_enum` 🙃 
```ruby
Season.where(name_cd: 0)
```

**Comment by drobny** [comment]
Hi @nicolasrouanne I think this might be a duplicate of https://github.com/lwe/simple_enum/issues/137, I think my fix as per https://github.com/lwe/simple_enum/pull/138 should work, would you mind bundling from that branch and letting me know whether you still encounter any issues?

**Comment by nicolasrouanne** [comment]
Hi @drobny, thanks for the quick answer 😄 

Yes, indeed, #138 does fix it:
```ruby
# app/models/season.rb
class Season < ActiveRecord::Base
  as_enum :name, low: 0, medium: 1, high: 2
end

# rails console
> Season.lows

+----+---------+---------------------------+---------------------------+
| id | name_cd | created_at                | updated_at                |
+----+---------+---------------------------+---------------------------+
| 1  | 0       | 2016-05-31 13:00:03 +0200 | 2016-05-31 13:00:03 +0200 |
+----+---------+---------------------------+---------------------------+
```

However, trying to _not pluralize_ doesn't work
```ruby
# app/models/season.rb
class Season < ActiveRecord::Base
  as_enum :name, low: 0, medium: 1, high: 2, pluralize_scopes: false
end

# rails console
> Season.low
NoMethodError: undefined method `low' for #<Class:0x007f8b6fb5f570>
```

**Comment by nicolasrouanne** [comment]
However, I see the same behaviour with #138  than with gem version `2.3.0` [which is said](https://github.com/lwe/simple_enum/issues/137) to work fine.

So I may be not fully understand how the feature works... 😉

**Comment by drobny** [comment]
That looks right to me, I am guessing you restarted / reloaded the console session after you added the `pluralize_scope: false` option in?

**Comment by nicolasrouanne** [comment]
Yes @drobny I did restart the console (2 or 3 times 🤣) after adding `pluralize_scopes: false`. But, as I said, this doesn't work with `2.3.0` either. So maybe it's something else...

**Comment by drobny** [comment]
Mmm, have you got a repo I can have a look at to do some testing against? The `pluralize_scopes` option was only introduced in version 2.3.1

**Comment by nicolasrouanne** [comment]
Hey @drobny, sorry for the late reply. Here is a[ simple repository](https://github.com/nicolasrouanne/simple_enum-singular-scopes) reproducing the issue. Thx

**Comment by drobny** [comment]
Thanks @nicolasrouanne for doing that, will look into it as soon as possible

**Comment by drobny** [comment]
Looks like if you define it like

`as_enum :name, low: 0, medium: 1, high: 2, pluralize_scopes: false` it doesn't work because pluralize_scopes gets shoved in as a name of an option.

If you do something like

`as_enum :name, [:low, :medium, :high], pluralize_scopes: false` then it should work but whether that is not flexible enough or not is another matter. What are your thoughts?

**Comment by nicolasrouanne** [comment]
Well it does work indeed!
However, what would happen if I want to use other indices? Such as
```rb
as_enum :name, low: 1, medium: 2, high: 3
```
> I actually have models in my code where I start the index at 1 instead of 0 😉. And I do like the option of being able to manually decide which integer value I choose for each item.

**Comment by drobny** [comment]
Actually @nicolasrouanne you could do something like

```
as_enum :name, { low: 1, medium: 2, high: 3 }, pluralize_scopes: false
```

with the current implementation which should allow you to do what you are describing 👍

**Comment by drobny** [comment]
@nicolasrouanne no worries, I should have spotted this sooner from your description - my bad sorry 🤦‍♂️

**Comment by hraynaud** [comment]
I'm having the exact same issue. It's not clear from following this thread though what the root cause is. I'm also upgrade a rails app from 3.2 to 5.2 and going from 1.6.1 to 2.3.1 
None of the solutions mentioned in this thread worked for me:
- setting pluralize_scopes: false -- fail
- I was already using an array of symbols e.g.  as_enum status: [:pending, :confirmed]
I saw in a related ticket that caching might be involved. 

Thanks

**Comment by drobny** [comment]
@hraynaud can you try pointing your Gemfile to the master repo instead of 2.3.1 and see if that fixes it? I think the proposed fix has not been release as a new patch version yet

**Comment by hraynaud** [comment]
@drobny @lwe Thanks for the reply. Sorry it took me a couple of days to get back to this. Pointing to the master branch works. 

Thanks for your help.

**Comment by lwe** [comment]
👍 awsome, thanks for checking, so I guess I'll release that as an upgrade, so everyone can benefit.

**Comment by lwe** [comment]
published 2.3.2 to rubygems, https://rubygems.org/gems/simple_enum/versions/2.3.2
